kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: {{ .Values.app_name }}-client
    env: {{ .Values.env }}
    role: {{ .Values.label_app_role }}
    name: {{ .Values.app_name }}-rt
  name: {{ .Values.app_name }}-rt
spec:
  to:
    kind: Service
    name: {{ .Values.app_name }}-client-svc
    weight: 100
  port:
    targetPort: {{ .Values.client_service_port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
