kind: Secret
apiVersion: v1
stringData:
  database-name: {{ .Values.postgresdb_params.database_name }}
  database-password: {{ .Values.postgresdb_params.database_password }}
  database-user: {{ .Values.postgresdb_params.database_user }}
metadata:
  labels:
    template: postgresql-persistent-template
    app: {{ .Values.app_name }}
    env: {{ .Values.env }}
    name: {{ .Values.postgresdb_params.database_secret_name }}
  name: {{ .Values.postgresdb_params.database_secret_name }}
type: Opaque